$(document).ready(function(){
    $(".owl-carousel").owlCarousel({
        autoplay:true,
        stagePadding:10,
        loop:true,
        margin:10,
        autoplayHoverPause:true,
        responsiveClass:true,
        responsive:{
            0:{
            items:1
            },
            600:{
                items:2
            },
            1000:{
                items:3,
            }
        }
    });
});